server:
  port: 8080

spring:
  application:
    name: task-manager

  profiles:
    active: dev

  logging:
    level:
      root: INFO
      org.springframework.web: DEBUG

  cloud:
    config:
      enabled: false